- name: configure mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - PyMySQL
    - cryptography

  - name: install mysql server
    ansible.builtin.package:
      name: mysql-server
      state: installed
  
  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
 
  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: mysql.daws-82s.cloud
    register: mysql_info #to display output
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "MySQL info: {{ mysql_info }}"

  - name: setup roop password
    ansible.builtin.command: " mysql_secure_installation --set-root-pass ExpenseApp@1 "
    when: mysql_info.failed is true

    # this script has executed without keeping and pass username and passwords as variable and without installing cryptography